// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_ton

import (
	context "context"

	address "github.com/xssnick/tonutils-go/address"

	mock "github.com/stretchr/testify/mock"

	tlb "github.com/xssnick/tonutils-go/tlb"

	ton "github.com/xssnick/tonutils-go/ton"
)

// TonAPI is an autogenerated mock type for the TonAPI type
type TonAPI struct {
	mock.Mock
}

type TonAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *TonAPI) EXPECT() *TonAPI_Expecter {
	return &TonAPI_Expecter{mock: &_m.Mock}
}

// CurrentMasterchainInfo provides a mock function with given fields: ctx
func (_m *TonAPI) CurrentMasterchainInfo(ctx context.Context) (*tlb.BlockInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentMasterchainInfo")
	}

	var r0 *tlb.BlockInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*tlb.BlockInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *tlb.BlockInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tlb.BlockInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TonAPI_CurrentMasterchainInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentMasterchainInfo'
type TonAPI_CurrentMasterchainInfo_Call struct {
	*mock.Call
}

// CurrentMasterchainInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TonAPI_Expecter) CurrentMasterchainInfo(ctx interface{}) *TonAPI_CurrentMasterchainInfo_Call {
	return &TonAPI_CurrentMasterchainInfo_Call{Call: _e.mock.On("CurrentMasterchainInfo", ctx)}
}

func (_c *TonAPI_CurrentMasterchainInfo_Call) Run(run func(ctx context.Context)) *TonAPI_CurrentMasterchainInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TonAPI_CurrentMasterchainInfo_Call) Return(_a0 *tlb.BlockInfo, _a1 error) *TonAPI_CurrentMasterchainInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TonAPI_CurrentMasterchainInfo_Call) RunAndReturn(run func(context.Context) (*tlb.BlockInfo, error)) *TonAPI_CurrentMasterchainInfo_Call {
	_c.Call.Return(run)
	return _c
}

// FindLastTransactionByInMsgHash provides a mock function with given fields: ctx, addr, msgHash, maxTxNumToScan
func (_m *TonAPI) FindLastTransactionByInMsgHash(ctx context.Context, addr *address.Address, msgHash []byte, maxTxNumToScan ...int) (*tlb.Transaction, error) {
	_va := make([]interface{}, len(maxTxNumToScan))
	for _i := range maxTxNumToScan {
		_va[_i] = maxTxNumToScan[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, addr, msgHash)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindLastTransactionByInMsgHash")
	}

	var r0 *tlb.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *address.Address, []byte, ...int) (*tlb.Transaction, error)); ok {
		return rf(ctx, addr, msgHash, maxTxNumToScan...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *address.Address, []byte, ...int) *tlb.Transaction); ok {
		r0 = rf(ctx, addr, msgHash, maxTxNumToScan...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tlb.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *address.Address, []byte, ...int) error); ok {
		r1 = rf(ctx, addr, msgHash, maxTxNumToScan...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TonAPI_FindLastTransactionByInMsgHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLastTransactionByInMsgHash'
type TonAPI_FindLastTransactionByInMsgHash_Call struct {
	*mock.Call
}

// FindLastTransactionByInMsgHash is a helper method to define mock.On call
//   - ctx context.Context
//   - addr *address.Address
//   - msgHash []byte
//   - maxTxNumToScan ...int
func (_e *TonAPI_Expecter) FindLastTransactionByInMsgHash(ctx interface{}, addr interface{}, msgHash interface{}, maxTxNumToScan ...interface{}) *TonAPI_FindLastTransactionByInMsgHash_Call {
	return &TonAPI_FindLastTransactionByInMsgHash_Call{Call: _e.mock.On("FindLastTransactionByInMsgHash",
		append([]interface{}{ctx, addr, msgHash}, maxTxNumToScan...)...)}
}

func (_c *TonAPI_FindLastTransactionByInMsgHash_Call) Run(run func(ctx context.Context, addr *address.Address, msgHash []byte, maxTxNumToScan ...int)) *TonAPI_FindLastTransactionByInMsgHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]int, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(int)
			}
		}
		run(args[0].(context.Context), args[1].(*address.Address), args[2].([]byte), variadicArgs...)
	})
	return _c
}

func (_c *TonAPI_FindLastTransactionByInMsgHash_Call) Return(_a0 *tlb.Transaction, _a1 error) *TonAPI_FindLastTransactionByInMsgHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TonAPI_FindLastTransactionByInMsgHash_Call) RunAndReturn(run func(context.Context, *address.Address, []byte, ...int) (*tlb.Transaction, error)) *TonAPI_FindLastTransactionByInMsgHash_Call {
	_c.Call.Return(run)
	return _c
}

// SendExternalMessage provides a mock function with given fields: ctx, msg
func (_m *TonAPI) SendExternalMessage(ctx context.Context, msg *tlb.ExternalMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendExternalMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tlb.ExternalMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TonAPI_SendExternalMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendExternalMessage'
type TonAPI_SendExternalMessage_Call struct {
	*mock.Call
}

// SendExternalMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *tlb.ExternalMessage
func (_e *TonAPI_Expecter) SendExternalMessage(ctx interface{}, msg interface{}) *TonAPI_SendExternalMessage_Call {
	return &TonAPI_SendExternalMessage_Call{Call: _e.mock.On("SendExternalMessage", ctx, msg)}
}

func (_c *TonAPI_SendExternalMessage_Call) Run(run func(ctx context.Context, msg *tlb.ExternalMessage)) *TonAPI_SendExternalMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tlb.ExternalMessage))
	})
	return _c
}

func (_c *TonAPI_SendExternalMessage_Call) Return(_a0 error) *TonAPI_SendExternalMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TonAPI_SendExternalMessage_Call) RunAndReturn(run func(context.Context, *tlb.ExternalMessage) error) *TonAPI_SendExternalMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendExternalMessageWaitTransaction provides a mock function with given fields: ctx, ext
func (_m *TonAPI) SendExternalMessageWaitTransaction(ctx context.Context, ext *tlb.ExternalMessage) (*tlb.Transaction, *tlb.BlockInfo, []byte, error) {
	ret := _m.Called(ctx, ext)

	if len(ret) == 0 {
		panic("no return value specified for SendExternalMessageWaitTransaction")
	}

	var r0 *tlb.Transaction
	var r1 *tlb.BlockInfo
	var r2 []byte
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, *tlb.ExternalMessage) (*tlb.Transaction, *tlb.BlockInfo, []byte, error)); ok {
		return rf(ctx, ext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *tlb.ExternalMessage) *tlb.Transaction); ok {
		r0 = rf(ctx, ext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tlb.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *tlb.ExternalMessage) *tlb.BlockInfo); ok {
		r1 = rf(ctx, ext)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*tlb.BlockInfo)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *tlb.ExternalMessage) []byte); ok {
		r2 = rf(ctx, ext)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]byte)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, *tlb.ExternalMessage) error); ok {
		r3 = rf(ctx, ext)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// TonAPI_SendExternalMessageWaitTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendExternalMessageWaitTransaction'
type TonAPI_SendExternalMessageWaitTransaction_Call struct {
	*mock.Call
}

// SendExternalMessageWaitTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - ext *tlb.ExternalMessage
func (_e *TonAPI_Expecter) SendExternalMessageWaitTransaction(ctx interface{}, ext interface{}) *TonAPI_SendExternalMessageWaitTransaction_Call {
	return &TonAPI_SendExternalMessageWaitTransaction_Call{Call: _e.mock.On("SendExternalMessageWaitTransaction", ctx, ext)}
}

func (_c *TonAPI_SendExternalMessageWaitTransaction_Call) Run(run func(ctx context.Context, ext *tlb.ExternalMessage)) *TonAPI_SendExternalMessageWaitTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tlb.ExternalMessage))
	})
	return _c
}

func (_c *TonAPI_SendExternalMessageWaitTransaction_Call) Return(_a0 *tlb.Transaction, _a1 *tlb.BlockInfo, _a2 []byte, _a3 error) *TonAPI_SendExternalMessageWaitTransaction_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *TonAPI_SendExternalMessageWaitTransaction_Call) RunAndReturn(run func(context.Context, *tlb.ExternalMessage) (*tlb.Transaction, *tlb.BlockInfo, []byte, error)) *TonAPI_SendExternalMessageWaitTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForBlock provides a mock function with given fields: seqno
func (_m *TonAPI) WaitForBlock(seqno uint32) ton.APIClientWrapped {
	ret := _m.Called(seqno)

	if len(ret) == 0 {
		panic("no return value specified for WaitForBlock")
	}

	var r0 ton.APIClientWrapped
	if rf, ok := ret.Get(0).(func(uint32) ton.APIClientWrapped); ok {
		r0 = rf(seqno)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ton.APIClientWrapped)
		}
	}

	return r0
}

// TonAPI_WaitForBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForBlock'
type TonAPI_WaitForBlock_Call struct {
	*mock.Call
}

// WaitForBlock is a helper method to define mock.On call
//   - seqno uint32
func (_e *TonAPI_Expecter) WaitForBlock(seqno interface{}) *TonAPI_WaitForBlock_Call {
	return &TonAPI_WaitForBlock_Call{Call: _e.mock.On("WaitForBlock", seqno)}
}

func (_c *TonAPI_WaitForBlock_Call) Run(run func(seqno uint32)) *TonAPI_WaitForBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint32))
	})
	return _c
}

func (_c *TonAPI_WaitForBlock_Call) Return(_a0 ton.APIClientWrapped) *TonAPI_WaitForBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TonAPI_WaitForBlock_Call) RunAndReturn(run func(uint32) ton.APIClientWrapped) *TonAPI_WaitForBlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewTonAPI creates a new instance of TonAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTonAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *TonAPI {
	mock := &TonAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
