# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: daily
    allow:
      - dependency-name: "github.com/smartcontractkit/chain-selectors"
      - dependency-name: "github.com/smartcontractkit/chainlink-aptos"
      - dependency-name: "github.com/smartcontractkit/chainlink-ccip/chains/solana"
      - dependency-name: "github.com/smartcontractkit/chainlink-testing-framework/framework"
      - dependency-name: "github.com/aptos-labs/aptos-go-sdk"
      - dependency-name: "github.com/ethereum/go-ethereum"
      - dependency-name: "github.com/gagliardetto/solana-go"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
