version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - goconst
    - gosec
    - intrange
    - loggercheck
    - makezero
    - misspell
    - mnd
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - paralleltest
    - prealloc
    - reassign
    - revive
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    goconst:
      min-len: 5
    govet:
      enable:
        - shadow
    nlreturn:
      block-size: 2
    revive:
      confidence: 1
      rules:
        - name: comment-spacings
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        - name: defer
        - name: dot-imports
        - name: early-return
        - name: empty-block
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: errorf
        - name: identical-branches
        - name: if-return
        - name: import-shadowing
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-import-alias
        - name: string-of-int
        - name: superfluous-else
        - name: time-equal
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: use-any
        - name: useless-break
        - name: var-naming
        - name: var-declaration
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unparam
        path: _test\.go
      - linters:
          - gosec
          - mnd
          - paralleltest
        path: ^e2e/
    paths:
      - sdk/evm/bindings
      - sdk/usbwallet
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/smartcontractkit/mcms
  exclusions:
    generated: lax
    paths:
      - sdk/evm/bindings
      - sdk/usbwallet
      - third_party$
      - builtin$
      - examples$
