// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	protocol "github.com/stellar/go-stellar-sdk/protocols/rpc"
	mock "github.com/stretchr/testify/mock"
)

// RpcClient is an autogenerated mock type for the RpcClient type
type RpcClient struct {
	mock.Mock
}

type RpcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RpcClient) EXPECT() *RpcClient_Expecter {
	return &RpcClient_Expecter{mock: &_m.Mock}
}

// GetEvents provides a mock function with given fields: ctx, req
func (_m *RpcClient) GetEvents(ctx context.Context, req protocol.GetEventsRequest) (protocol.GetEventsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 protocol.GetEventsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetEventsRequest) (protocol.GetEventsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetEventsRequest) protocol.GetEventsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.GetEventsResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.GetEventsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RpcClient_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type RpcClient_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - req protocol.GetEventsRequest
func (_e *RpcClient_Expecter) GetEvents(ctx interface{}, req interface{}) *RpcClient_GetEvents_Call {
	return &RpcClient_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, req)}
}

func (_c *RpcClient_GetEvents_Call) Run(run func(ctx context.Context, req protocol.GetEventsRequest)) *RpcClient_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.GetEventsRequest))
	})
	return _c
}

func (_c *RpcClient_GetEvents_Call) Return(_a0 protocol.GetEventsResponse, _a1 error) *RpcClient_GetEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RpcClient_GetEvents_Call) RunAndReturn(run func(context.Context, protocol.GetEventsRequest) (protocol.GetEventsResponse, error)) *RpcClient_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetLedgerEntries provides a mock function with given fields: ctx, req
func (_m *RpcClient) GetLedgerEntries(ctx context.Context, req protocol.GetLedgerEntriesRequest) (protocol.GetLedgerEntriesResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetLedgerEntries")
	}

	var r0 protocol.GetLedgerEntriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetLedgerEntriesRequest) (protocol.GetLedgerEntriesResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetLedgerEntriesRequest) protocol.GetLedgerEntriesResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.GetLedgerEntriesResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.GetLedgerEntriesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RpcClient_GetLedgerEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLedgerEntries'
type RpcClient_GetLedgerEntries_Call struct {
	*mock.Call
}

// GetLedgerEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - req protocol.GetLedgerEntriesRequest
func (_e *RpcClient_Expecter) GetLedgerEntries(ctx interface{}, req interface{}) *RpcClient_GetLedgerEntries_Call {
	return &RpcClient_GetLedgerEntries_Call{Call: _e.mock.On("GetLedgerEntries", ctx, req)}
}

func (_c *RpcClient_GetLedgerEntries_Call) Run(run func(ctx context.Context, req protocol.GetLedgerEntriesRequest)) *RpcClient_GetLedgerEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.GetLedgerEntriesRequest))
	})
	return _c
}

func (_c *RpcClient_GetLedgerEntries_Call) Return(_a0 protocol.GetLedgerEntriesResponse, _a1 error) *RpcClient_GetLedgerEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RpcClient_GetLedgerEntries_Call) RunAndReturn(run func(context.Context, protocol.GetLedgerEntriesRequest) (protocol.GetLedgerEntriesResponse, error)) *RpcClient_GetLedgerEntries_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransaction provides a mock function with given fields: ctx, req
func (_m *RpcClient) GetTransaction(ctx context.Context, req protocol.GetTransactionRequest) (protocol.GetTransactionResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 protocol.GetTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetTransactionRequest) (protocol.GetTransactionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetTransactionRequest) protocol.GetTransactionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.GetTransactionResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.GetTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RpcClient_GetTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransaction'
type RpcClient_GetTransaction_Call struct {
	*mock.Call
}

// GetTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - req protocol.GetTransactionRequest
func (_e *RpcClient_Expecter) GetTransaction(ctx interface{}, req interface{}) *RpcClient_GetTransaction_Call {
	return &RpcClient_GetTransaction_Call{Call: _e.mock.On("GetTransaction", ctx, req)}
}

func (_c *RpcClient_GetTransaction_Call) Run(run func(ctx context.Context, req protocol.GetTransactionRequest)) *RpcClient_GetTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.GetTransactionRequest))
	})
	return _c
}

func (_c *RpcClient_GetTransaction_Call) Return(_a0 protocol.GetTransactionResponse, _a1 error) *RpcClient_GetTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RpcClient_GetTransaction_Call) RunAndReturn(run func(context.Context, protocol.GetTransactionRequest) (protocol.GetTransactionResponse, error)) *RpcClient_GetTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SendTransaction provides a mock function with given fields: ctx, req
func (_m *RpcClient) SendTransaction(ctx context.Context, req protocol.SendTransactionRequest) (protocol.SendTransactionResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendTransaction")
	}

	var r0 protocol.SendTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.SendTransactionRequest) (protocol.SendTransactionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.SendTransactionRequest) protocol.SendTransactionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.SendTransactionResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.SendTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RpcClient_SendTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTransaction'
type RpcClient_SendTransaction_Call struct {
	*mock.Call
}

// SendTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - req protocol.SendTransactionRequest
func (_e *RpcClient_Expecter) SendTransaction(ctx interface{}, req interface{}) *RpcClient_SendTransaction_Call {
	return &RpcClient_SendTransaction_Call{Call: _e.mock.On("SendTransaction", ctx, req)}
}

func (_c *RpcClient_SendTransaction_Call) Run(run func(ctx context.Context, req protocol.SendTransactionRequest)) *RpcClient_SendTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.SendTransactionRequest))
	})
	return _c
}

func (_c *RpcClient_SendTransaction_Call) Return(_a0 protocol.SendTransactionResponse, _a1 error) *RpcClient_SendTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RpcClient_SendTransaction_Call) RunAndReturn(run func(context.Context, protocol.SendTransactionRequest) (protocol.SendTransactionResponse, error)) *RpcClient_SendTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SimulateTransaction provides a mock function with given fields: ctx, req
func (_m *RpcClient) SimulateTransaction(ctx context.Context, req protocol.SimulateTransactionRequest) (protocol.SimulateTransactionResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SimulateTransaction")
	}

	var r0 protocol.SimulateTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.SimulateTransactionRequest) (protocol.SimulateTransactionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.SimulateTransactionRequest) protocol.SimulateTransactionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.SimulateTransactionResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.SimulateTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RpcClient_SimulateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulateTransaction'
type RpcClient_SimulateTransaction_Call struct {
	*mock.Call
}

// SimulateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - req protocol.SimulateTransactionRequest
func (_e *RpcClient_Expecter) SimulateTransaction(ctx interface{}, req interface{}) *RpcClient_SimulateTransaction_Call {
	return &RpcClient_SimulateTransaction_Call{Call: _e.mock.On("SimulateTransaction", ctx, req)}
}

func (_c *RpcClient_SimulateTransaction_Call) Run(run func(ctx context.Context, req protocol.SimulateTransactionRequest)) *RpcClient_SimulateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.SimulateTransactionRequest))
	})
	return _c
}

func (_c *RpcClient_SimulateTransaction_Call) Return(_a0 protocol.SimulateTransactionResponse, _a1 error) *RpcClient_SimulateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RpcClient_SimulateTransaction_Call) RunAndReturn(run func(context.Context, protocol.SimulateTransactionRequest) (protocol.SimulateTransactionResponse, error)) *RpcClient_SimulateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewRpcClient creates a new instance of RpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RpcClient {
	mock := &RpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
