// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	xdr "github.com/stellar/go-stellar-sdk/xdr"
	mock "github.com/stretchr/testify/mock"
)

// Signer is an autogenerated mock type for the Signer type
type Signer struct {
	mock.Mock
}

type Signer_Expecter struct {
	mock *mock.Mock
}

func (_m *Signer) EXPECT() *Signer_Expecter {
	return &Signer_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *Signer) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Signer_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type Signer_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *Signer_Expecter) Address() *Signer_Address_Call {
	return &Signer_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *Signer_Address_Call) Run(run func()) *Signer_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Signer_Address_Call) Return(_a0 string) *Signer_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Signer_Address_Call) RunAndReturn(run func() string) *Signer_Address_Call {
	_c.Call.Return(run)
	return _c
}

// SignDecorated provides a mock function with given fields: _a0
func (_m *Signer) SignDecorated(_a0 []byte) (xdr.DecoratedSignature, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SignDecorated")
	}

	var r0 xdr.DecoratedSignature
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (xdr.DecoratedSignature, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) xdr.DecoratedSignature); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(xdr.DecoratedSignature)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Signer_SignDecorated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignDecorated'
type Signer_SignDecorated_Call struct {
	*mock.Call
}

// SignDecorated is a helper method to define mock.On call
//   - _a0 []byte
func (_e *Signer_Expecter) SignDecorated(_a0 interface{}) *Signer_SignDecorated_Call {
	return &Signer_SignDecorated_Call{Call: _e.mock.On("SignDecorated", _a0)}
}

func (_c *Signer_SignDecorated_Call) Run(run func(_a0 []byte)) *Signer_SignDecorated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *Signer_SignDecorated_Call) Return(_a0 xdr.DecoratedSignature, _a1 error) *Signer_SignDecorated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Signer_SignDecorated_Call) RunAndReturn(run func([]byte) (xdr.DecoratedSignature, error)) *Signer_SignDecorated_Call {
	_c.Call.Return(run)
	return _c
}

// NewSigner creates a new instance of Signer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Signer {
	mock := &Signer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
