// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	types "github.com/smartcontractkit/mcms/types"
	mock "github.com/stretchr/testify/mock"
)

// ProposalInterface is an autogenerated mock type for the ProposalInterface type
type ProposalInterface struct {
	mock.Mock
}

type ProposalInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ProposalInterface) EXPECT() *ProposalInterface_Expecter {
	return &ProposalInterface_Expecter{mock: &_m.Mock}
}

// AppendSignature provides a mock function with given fields: signature
func (_m *ProposalInterface) AppendSignature(signature types.Signature) {
	_m.Called(signature)
}

// ProposalInterface_AppendSignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendSignature'
type ProposalInterface_AppendSignature_Call struct {
	*mock.Call
}

// AppendSignature is a helper method to define mock.On call
//   - signature types.Signature
func (_e *ProposalInterface_Expecter) AppendSignature(signature interface{}) *ProposalInterface_AppendSignature_Call {
	return &ProposalInterface_AppendSignature_Call{Call: _e.mock.On("AppendSignature", signature)}
}

func (_c *ProposalInterface_AppendSignature_Call) Run(run func(signature types.Signature)) *ProposalInterface_AppendSignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Signature))
	})
	return _c
}

func (_c *ProposalInterface_AppendSignature_Call) Return() *ProposalInterface_AppendSignature_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProposalInterface_AppendSignature_Call) RunAndReturn(run func(types.Signature)) *ProposalInterface_AppendSignature_Call {
	_c.Run(run)
	return _c
}

// ChainMetadatas provides a mock function with no fields
func (_m *ProposalInterface) ChainMetadatas() map[types.ChainSelector]types.ChainMetadata {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChainMetadatas")
	}

	var r0 map[types.ChainSelector]types.ChainMetadata
	if rf, ok := ret.Get(0).(func() map[types.ChainSelector]types.ChainMetadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.ChainSelector]types.ChainMetadata)
		}
	}

	return r0
}

// ProposalInterface_ChainMetadatas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChainMetadatas'
type ProposalInterface_ChainMetadatas_Call struct {
	*mock.Call
}

// ChainMetadatas is a helper method to define mock.On call
func (_e *ProposalInterface_Expecter) ChainMetadatas() *ProposalInterface_ChainMetadatas_Call {
	return &ProposalInterface_ChainMetadatas_Call{Call: _e.mock.On("ChainMetadatas")}
}

func (_c *ProposalInterface_ChainMetadatas_Call) Run(run func()) *ProposalInterface_ChainMetadatas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProposalInterface_ChainMetadatas_Call) Return(_a0 map[types.ChainSelector]types.ChainMetadata) *ProposalInterface_ChainMetadatas_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProposalInterface_ChainMetadatas_Call) RunAndReturn(run func() map[types.ChainSelector]types.ChainMetadata) *ProposalInterface_ChainMetadatas_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionCounts provides a mock function with no fields
func (_m *ProposalInterface) TransactionCounts() map[types.ChainSelector]uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TransactionCounts")
	}

	var r0 map[types.ChainSelector]uint64
	if rf, ok := ret.Get(0).(func() map[types.ChainSelector]uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.ChainSelector]uint64)
		}
	}

	return r0
}

// ProposalInterface_TransactionCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionCounts'
type ProposalInterface_TransactionCounts_Call struct {
	*mock.Call
}

// TransactionCounts is a helper method to define mock.On call
func (_e *ProposalInterface_Expecter) TransactionCounts() *ProposalInterface_TransactionCounts_Call {
	return &ProposalInterface_TransactionCounts_Call{Call: _e.mock.On("TransactionCounts")}
}

func (_c *ProposalInterface_TransactionCounts_Call) Run(run func()) *ProposalInterface_TransactionCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProposalInterface_TransactionCounts_Call) Return(_a0 map[types.ChainSelector]uint64) *ProposalInterface_TransactionCounts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProposalInterface_TransactionCounts_Call) RunAndReturn(run func() map[types.ChainSelector]uint64) *ProposalInterface_TransactionCounts_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with no fields
func (_m *ProposalInterface) Validate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProposalInterface_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ProposalInterface_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *ProposalInterface_Expecter) Validate() *ProposalInterface_Validate_Call {
	return &ProposalInterface_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *ProposalInterface_Validate_Call) Run(run func()) *ProposalInterface_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProposalInterface_Validate_Call) Return(_a0 error) *ProposalInterface_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProposalInterface_Validate_Call) RunAndReturn(run func() error) *ProposalInterface_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// setChainMetadata provides a mock function with given fields: chainSelector, metadata
func (_m *ProposalInterface) setChainMetadata(chainSelector types.ChainSelector, metadata types.ChainMetadata) {
	_m.Called(chainSelector, metadata)
}

// ProposalInterface_setChainMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setChainMetadata'
type ProposalInterface_setChainMetadata_Call struct {
	*mock.Call
}

// setChainMetadata is a helper method to define mock.On call
//   - chainSelector types.ChainSelector
//   - metadata types.ChainMetadata
func (_e *ProposalInterface_Expecter) setChainMetadata(chainSelector interface{}, metadata interface{}) *ProposalInterface_setChainMetadata_Call {
	return &ProposalInterface_setChainMetadata_Call{Call: _e.mock.On("setChainMetadata", chainSelector, metadata)}
}

func (_c *ProposalInterface_setChainMetadata_Call) Run(run func(chainSelector types.ChainSelector, metadata types.ChainMetadata)) *ProposalInterface_setChainMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ChainSelector), args[1].(types.ChainMetadata))
	})
	return _c
}

func (_c *ProposalInterface_setChainMetadata_Call) Return() *ProposalInterface_setChainMetadata_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProposalInterface_setChainMetadata_Call) RunAndReturn(run func(types.ChainSelector, types.ChainMetadata)) *ProposalInterface_setChainMetadata_Call {
	_c.Run(run)
	return _c
}

// NewProposalInterface creates a new instance of ProposalInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProposalInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProposalInterface {
	mock := &ProposalInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
