// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProposalOption is an autogenerated mock type for the ProposalOption type
type ProposalOption struct {
	mock.Mock
}

type ProposalOption_Expecter struct {
	mock *mock.Mock
}

func (_m *ProposalOption) EXPECT() *ProposalOption_Expecter {
	return &ProposalOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *ProposalOption) Execute(_a0 *mcms.proposalOptions) {
	_m.Called(_a0)
}

// ProposalOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ProposalOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *mcms.proposalOptions
func (_e *ProposalOption_Expecter) Execute(_a0 interface{}) *ProposalOption_Execute_Call {
	return &ProposalOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *ProposalOption_Execute_Call) Run(run func(_a0 *mcms.proposalOptions)) *ProposalOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*mcms.proposalOptions))
	})
	return _c
}

func (_c *ProposalOption_Execute_Call) Return() *ProposalOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProposalOption_Execute_Call) RunAndReturn(run func(*mcms.proposalOptions)) *ProposalOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewProposalOption creates a new instance of ProposalOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProposalOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProposalOption {
	mock := &ProposalOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
