// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"
)

// signer is an autogenerated mock type for the signer type
type signer struct {
	mock.Mock
}

type signer_Expecter struct {
	mock *mock.Mock
}

func (_m *signer) EXPECT() *signer_Expecter {
	return &signer_Expecter{mock: &_m.Mock}
}

// GetAddress provides a mock function with no fields
func (_m *signer) GetAddress() (common.Address, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAddress")
	}

	var r0 common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func() (common.Address, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() common.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// signer_GetAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddress'
type signer_GetAddress_Call struct {
	*mock.Call
}

// GetAddress is a helper method to define mock.On call
func (_e *signer_Expecter) GetAddress() *signer_GetAddress_Call {
	return &signer_GetAddress_Call{Call: _e.mock.On("GetAddress")}
}

func (_c *signer_GetAddress_Call) Run(run func()) *signer_GetAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *signer_GetAddress_Call) Return(_a0 common.Address, _a1 error) *signer_GetAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *signer_GetAddress_Call) RunAndReturn(run func() (common.Address, error)) *signer_GetAddress_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function with given fields: payload
func (_m *signer) Sign(payload []byte) ([]byte, error) {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// signer_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type signer_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - payload []byte
func (_e *signer_Expecter) Sign(payload interface{}) *signer_Sign_Call {
	return &signer_Sign_Call{Call: _e.mock.On("Sign", payload)}
}

func (_c *signer_Sign_Call) Run(run func(payload []byte)) *signer_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *signer_Sign_Call) Return(_a0 []byte, _a1 error) *signer_Sign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *signer_Sign_Call) RunAndReturn(run func([]byte) ([]byte, error)) *signer_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// newSigner creates a new instance of signer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *signer {
	mock := &signer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
