// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_apiv2

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v2 "github.com/digital-asset/dazl-client/v8/go/api/com/daml/ledger/api/v2"
)

// CommandServiceClient is an autogenerated mock type for the CommandServiceClient type
type CommandServiceClient struct {
	mock.Mock
}

type CommandServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CommandServiceClient) EXPECT() *CommandServiceClient_Expecter {
	return &CommandServiceClient_Expecter{mock: &_m.Mock}
}

// SubmitAndWait provides a mock function with given fields: ctx, in, opts
func (_m *CommandServiceClient) SubmitAndWait(ctx context.Context, in *v2.SubmitAndWaitRequest, opts ...grpc.CallOption) (*v2.SubmitAndWaitResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubmitAndWait")
	}

	var r0 *v2.SubmitAndWaitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.SubmitAndWaitRequest, ...grpc.CallOption) (*v2.SubmitAndWaitResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.SubmitAndWaitRequest, ...grpc.CallOption) *v2.SubmitAndWaitResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.SubmitAndWaitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.SubmitAndWaitRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommandServiceClient_SubmitAndWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitAndWait'
type CommandServiceClient_SubmitAndWait_Call struct {
	*mock.Call
}

// SubmitAndWait is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.SubmitAndWaitRequest
//   - opts ...grpc.CallOption
func (_e *CommandServiceClient_Expecter) SubmitAndWait(ctx interface{}, in interface{}, opts ...interface{}) *CommandServiceClient_SubmitAndWait_Call {
	return &CommandServiceClient_SubmitAndWait_Call{Call: _e.mock.On("SubmitAndWait",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CommandServiceClient_SubmitAndWait_Call) Run(run func(ctx context.Context, in *v2.SubmitAndWaitRequest, opts ...grpc.CallOption)) *CommandServiceClient_SubmitAndWait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.SubmitAndWaitRequest), variadicArgs...)
	})
	return _c
}

func (_c *CommandServiceClient_SubmitAndWait_Call) Return(_a0 *v2.SubmitAndWaitResponse, _a1 error) *CommandServiceClient_SubmitAndWait_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommandServiceClient_SubmitAndWait_Call) RunAndReturn(run func(context.Context, *v2.SubmitAndWaitRequest, ...grpc.CallOption) (*v2.SubmitAndWaitResponse, error)) *CommandServiceClient_SubmitAndWait_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitAndWaitForReassignment provides a mock function with given fields: ctx, in, opts
func (_m *CommandServiceClient) SubmitAndWaitForReassignment(ctx context.Context, in *v2.SubmitAndWaitForReassignmentRequest, opts ...grpc.CallOption) (*v2.SubmitAndWaitForReassignmentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubmitAndWaitForReassignment")
	}

	var r0 *v2.SubmitAndWaitForReassignmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.SubmitAndWaitForReassignmentRequest, ...grpc.CallOption) (*v2.SubmitAndWaitForReassignmentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.SubmitAndWaitForReassignmentRequest, ...grpc.CallOption) *v2.SubmitAndWaitForReassignmentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.SubmitAndWaitForReassignmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.SubmitAndWaitForReassignmentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommandServiceClient_SubmitAndWaitForReassignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitAndWaitForReassignment'
type CommandServiceClient_SubmitAndWaitForReassignment_Call struct {
	*mock.Call
}

// SubmitAndWaitForReassignment is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.SubmitAndWaitForReassignmentRequest
//   - opts ...grpc.CallOption
func (_e *CommandServiceClient_Expecter) SubmitAndWaitForReassignment(ctx interface{}, in interface{}, opts ...interface{}) *CommandServiceClient_SubmitAndWaitForReassignment_Call {
	return &CommandServiceClient_SubmitAndWaitForReassignment_Call{Call: _e.mock.On("SubmitAndWaitForReassignment",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CommandServiceClient_SubmitAndWaitForReassignment_Call) Run(run func(ctx context.Context, in *v2.SubmitAndWaitForReassignmentRequest, opts ...grpc.CallOption)) *CommandServiceClient_SubmitAndWaitForReassignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.SubmitAndWaitForReassignmentRequest), variadicArgs...)
	})
	return _c
}

func (_c *CommandServiceClient_SubmitAndWaitForReassignment_Call) Return(_a0 *v2.SubmitAndWaitForReassignmentResponse, _a1 error) *CommandServiceClient_SubmitAndWaitForReassignment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommandServiceClient_SubmitAndWaitForReassignment_Call) RunAndReturn(run func(context.Context, *v2.SubmitAndWaitForReassignmentRequest, ...grpc.CallOption) (*v2.SubmitAndWaitForReassignmentResponse, error)) *CommandServiceClient_SubmitAndWaitForReassignment_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitAndWaitForTransaction provides a mock function with given fields: ctx, in, opts
func (_m *CommandServiceClient) SubmitAndWaitForTransaction(ctx context.Context, in *v2.SubmitAndWaitForTransactionRequest, opts ...grpc.CallOption) (*v2.SubmitAndWaitForTransactionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubmitAndWaitForTransaction")
	}

	var r0 *v2.SubmitAndWaitForTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.SubmitAndWaitForTransactionRequest, ...grpc.CallOption) (*v2.SubmitAndWaitForTransactionResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.SubmitAndWaitForTransactionRequest, ...grpc.CallOption) *v2.SubmitAndWaitForTransactionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.SubmitAndWaitForTransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.SubmitAndWaitForTransactionRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommandServiceClient_SubmitAndWaitForTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitAndWaitForTransaction'
type CommandServiceClient_SubmitAndWaitForTransaction_Call struct {
	*mock.Call
}

// SubmitAndWaitForTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.SubmitAndWaitForTransactionRequest
//   - opts ...grpc.CallOption
func (_e *CommandServiceClient_Expecter) SubmitAndWaitForTransaction(ctx interface{}, in interface{}, opts ...interface{}) *CommandServiceClient_SubmitAndWaitForTransaction_Call {
	return &CommandServiceClient_SubmitAndWaitForTransaction_Call{Call: _e.mock.On("SubmitAndWaitForTransaction",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CommandServiceClient_SubmitAndWaitForTransaction_Call) Run(run func(ctx context.Context, in *v2.SubmitAndWaitForTransactionRequest, opts ...grpc.CallOption)) *CommandServiceClient_SubmitAndWaitForTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v2.SubmitAndWaitForTransactionRequest), variadicArgs...)
	})
	return _c
}

func (_c *CommandServiceClient_SubmitAndWaitForTransaction_Call) Return(_a0 *v2.SubmitAndWaitForTransactionResponse, _a1 error) *CommandServiceClient_SubmitAndWaitForTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommandServiceClient_SubmitAndWaitForTransaction_Call) RunAndReturn(run func(context.Context, *v2.SubmitAndWaitForTransactionRequest, ...grpc.CallOption) (*v2.SubmitAndWaitForTransactionResponse, error)) *CommandServiceClient_SubmitAndWaitForTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommandServiceClient creates a new instance of CommandServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandServiceClient {
	mock := &CommandServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
