// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mcms "github.com/smartcontractkit/mcms"
	mock "github.com/stretchr/testify/mock"

	sdk "github.com/smartcontractkit/mcms/sdk"

	types "github.com/smartcontractkit/mcms/types"
)

// InspectorFetcher is an autogenerated mock type for the InspectorFetcher type
type InspectorFetcher struct {
	mock.Mock
}

type InspectorFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *InspectorFetcher) EXPECT() *InspectorFetcher_Expecter {
	return &InspectorFetcher_Expecter{mock: &_m.Mock}
}

// FetchInspectors provides a mock function with given fields: chainMetadata, proposal
func (_m *InspectorFetcher) FetchInspectors(chainMetadata map[types.ChainSelector]types.ChainMetadata, proposal *mcms.TimelockProposal) (map[types.ChainSelector]sdk.Inspector, error) {
	ret := _m.Called(chainMetadata, proposal)

	if len(ret) == 0 {
		panic("no return value specified for FetchInspectors")
	}

	var r0 map[types.ChainSelector]sdk.Inspector
	var r1 error
	if rf, ok := ret.Get(0).(func(map[types.ChainSelector]types.ChainMetadata, *mcms.TimelockProposal) (map[types.ChainSelector]sdk.Inspector, error)); ok {
		return rf(chainMetadata, proposal)
	}
	if rf, ok := ret.Get(0).(func(map[types.ChainSelector]types.ChainMetadata, *mcms.TimelockProposal) map[types.ChainSelector]sdk.Inspector); ok {
		r0 = rf(chainMetadata, proposal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.ChainSelector]sdk.Inspector)
		}
	}

	if rf, ok := ret.Get(1).(func(map[types.ChainSelector]types.ChainMetadata, *mcms.TimelockProposal) error); ok {
		r1 = rf(chainMetadata, proposal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InspectorFetcher_FetchInspectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchInspectors'
type InspectorFetcher_FetchInspectors_Call struct {
	*mock.Call
}

// FetchInspectors is a helper method to define mock.On call
//   - chainMetadata map[types.ChainSelector]types.ChainMetadata
//   - proposal *mcms.TimelockProposal
func (_e *InspectorFetcher_Expecter) FetchInspectors(chainMetadata interface{}, proposal interface{}) *InspectorFetcher_FetchInspectors_Call {
	return &InspectorFetcher_FetchInspectors_Call{Call: _e.mock.On("FetchInspectors", chainMetadata, proposal)}
}

func (_c *InspectorFetcher_FetchInspectors_Call) Run(run func(chainMetadata map[types.ChainSelector]types.ChainMetadata, proposal *mcms.TimelockProposal)) *InspectorFetcher_FetchInspectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[types.ChainSelector]types.ChainMetadata), args[1].(*mcms.TimelockProposal))
	})
	return _c
}

func (_c *InspectorFetcher_FetchInspectors_Call) Return(_a0 map[types.ChainSelector]sdk.Inspector, _a1 error) *InspectorFetcher_FetchInspectors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InspectorFetcher_FetchInspectors_Call) RunAndReturn(run func(map[types.ChainSelector]types.ChainMetadata, *mcms.TimelockProposal) (map[types.ChainSelector]sdk.Inspector, error)) *InspectorFetcher_FetchInspectors_Call {
	_c.Call.Return(run)
	return _c
}

// NewInspectorFetcher creates a new instance of InspectorFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInspectorFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *InspectorFetcher {
	mock := &InspectorFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
