// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	sdk "github.com/smartcontractkit/mcms/sdk"
	mock "github.com/stretchr/testify/mock"
)

// BlockChains is an autogenerated mock type for the BlockChains type
type BlockChains struct {
	mock.Mock
}

type BlockChains_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockChains) EXPECT() *BlockChains_Expecter {
	return &BlockChains_Expecter{mock: &_m.Mock}
}

// AptosChains provides a mock function with no fields
func (_m *BlockChains) AptosChains() map[uint64]sdk.ChainClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AptosChains")
	}

	var r0 map[uint64]sdk.ChainClient
	if rf, ok := ret.Get(0).(func() map[uint64]sdk.ChainClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]sdk.ChainClient)
		}
	}

	return r0
}

// BlockChains_AptosChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AptosChains'
type BlockChains_AptosChains_Call struct {
	*mock.Call
}

// AptosChains is a helper method to define mock.On call
func (_e *BlockChains_Expecter) AptosChains() *BlockChains_AptosChains_Call {
	return &BlockChains_AptosChains_Call{Call: _e.mock.On("AptosChains")}
}

func (_c *BlockChains_AptosChains_Call) Run(run func()) *BlockChains_AptosChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockChains_AptosChains_Call) Return(_a0 map[uint64]sdk.ChainClient) *BlockChains_AptosChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockChains_AptosChains_Call) RunAndReturn(run func() map[uint64]sdk.ChainClient) *BlockChains_AptosChains_Call {
	_c.Call.Return(run)
	return _c
}

// EVMChains provides a mock function with no fields
func (_m *BlockChains) EVMChains() map[uint64]sdk.EVMChainClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EVMChains")
	}

	var r0 map[uint64]sdk.EVMChainClient
	if rf, ok := ret.Get(0).(func() map[uint64]sdk.EVMChainClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]sdk.EVMChainClient)
		}
	}

	return r0
}

// BlockChains_EVMChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EVMChains'
type BlockChains_EVMChains_Call struct {
	*mock.Call
}

// EVMChains is a helper method to define mock.On call
func (_e *BlockChains_Expecter) EVMChains() *BlockChains_EVMChains_Call {
	return &BlockChains_EVMChains_Call{Call: _e.mock.On("EVMChains")}
}

func (_c *BlockChains_EVMChains_Call) Run(run func()) *BlockChains_EVMChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockChains_EVMChains_Call) Return(_a0 map[uint64]sdk.EVMChainClient) *BlockChains_EVMChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockChains_EVMChains_Call) RunAndReturn(run func() map[uint64]sdk.EVMChainClient) *BlockChains_EVMChains_Call {
	_c.Call.Return(run)
	return _c
}

// SolanaChains provides a mock function with no fields
func (_m *BlockChains) SolanaChains() map[uint64]sdk.SolanaChainClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SolanaChains")
	}

	var r0 map[uint64]sdk.SolanaChainClient
	if rf, ok := ret.Get(0).(func() map[uint64]sdk.SolanaChainClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]sdk.SolanaChainClient)
		}
	}

	return r0
}

// BlockChains_SolanaChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SolanaChains'
type BlockChains_SolanaChains_Call struct {
	*mock.Call
}

// SolanaChains is a helper method to define mock.On call
func (_e *BlockChains_Expecter) SolanaChains() *BlockChains_SolanaChains_Call {
	return &BlockChains_SolanaChains_Call{Call: _e.mock.On("SolanaChains")}
}

func (_c *BlockChains_SolanaChains_Call) Run(run func()) *BlockChains_SolanaChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockChains_SolanaChains_Call) Return(_a0 map[uint64]sdk.SolanaChainClient) *BlockChains_SolanaChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockChains_SolanaChains_Call) RunAndReturn(run func() map[uint64]sdk.SolanaChainClient) *BlockChains_SolanaChains_Call {
	_c.Call.Return(run)
	return _c
}

// SuiChains provides a mock function with no fields
func (_m *BlockChains) SuiChains() map[uint64]sdk.SuiChainClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SuiChains")
	}

	var r0 map[uint64]sdk.SuiChainClient
	if rf, ok := ret.Get(0).(func() map[uint64]sdk.SuiChainClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]sdk.SuiChainClient)
		}
	}

	return r0
}

// BlockChains_SuiChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuiChains'
type BlockChains_SuiChains_Call struct {
	*mock.Call
}

// SuiChains is a helper method to define mock.On call
func (_e *BlockChains_Expecter) SuiChains() *BlockChains_SuiChains_Call {
	return &BlockChains_SuiChains_Call{Call: _e.mock.On("SuiChains")}
}

func (_c *BlockChains_SuiChains_Call) Run(run func()) *BlockChains_SuiChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockChains_SuiChains_Call) Return(_a0 map[uint64]sdk.SuiChainClient) *BlockChains_SuiChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockChains_SuiChains_Call) RunAndReturn(run func() map[uint64]sdk.SuiChainClient) *BlockChains_SuiChains_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlockChains creates a new instance of BlockChains. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockChains(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockChains {
	mock := &BlockChains{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
