// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	aptos "github.com/aptos-labs/aptos-go-sdk"
	mock "github.com/stretchr/testify/mock"

	rpc "github.com/gagliardetto/solana-go/rpc"

	sdk "github.com/smartcontractkit/mcms/sdk"

	sui "github.com/block-vision/sui-go-sdk/sui"
)

// ChainAccess is an autogenerated mock type for the ChainAccess type
type ChainAccess struct {
	mock.Mock
}

type ChainAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *ChainAccess) EXPECT() *ChainAccess_Expecter {
	return &ChainAccess_Expecter{mock: &_m.Mock}
}

// AptosClient provides a mock function with given fields: selector
func (_m *ChainAccess) AptosClient(selector uint64) (aptos.AptosRpcClient, bool) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for AptosClient")
	}

	var r0 aptos.AptosRpcClient
	var r1 bool
	if rf, ok := ret.Get(0).(func(uint64) (aptos.AptosRpcClient, bool)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(uint64) aptos.AptosRpcClient); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aptos.AptosRpcClient)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ChainAccess_AptosClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AptosClient'
type ChainAccess_AptosClient_Call struct {
	*mock.Call
}

// AptosClient is a helper method to define mock.On call
//   - selector uint64
func (_e *ChainAccess_Expecter) AptosClient(selector interface{}) *ChainAccess_AptosClient_Call {
	return &ChainAccess_AptosClient_Call{Call: _e.mock.On("AptosClient", selector)}
}

func (_c *ChainAccess_AptosClient_Call) Run(run func(selector uint64)) *ChainAccess_AptosClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ChainAccess_AptosClient_Call) Return(_a0 aptos.AptosRpcClient, _a1 bool) *ChainAccess_AptosClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChainAccess_AptosClient_Call) RunAndReturn(run func(uint64) (aptos.AptosRpcClient, bool)) *ChainAccess_AptosClient_Call {
	_c.Call.Return(run)
	return _c
}

// EVMClient provides a mock function with given fields: selector
func (_m *ChainAccess) EVMClient(selector uint64) (sdk.ContractDeployBackend, bool) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for EVMClient")
	}

	var r0 sdk.ContractDeployBackend
	var r1 bool
	if rf, ok := ret.Get(0).(func(uint64) (sdk.ContractDeployBackend, bool)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(uint64) sdk.ContractDeployBackend); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sdk.ContractDeployBackend)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ChainAccess_EVMClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EVMClient'
type ChainAccess_EVMClient_Call struct {
	*mock.Call
}

// EVMClient is a helper method to define mock.On call
//   - selector uint64
func (_e *ChainAccess_Expecter) EVMClient(selector interface{}) *ChainAccess_EVMClient_Call {
	return &ChainAccess_EVMClient_Call{Call: _e.mock.On("EVMClient", selector)}
}

func (_c *ChainAccess_EVMClient_Call) Run(run func(selector uint64)) *ChainAccess_EVMClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ChainAccess_EVMClient_Call) Return(_a0 sdk.ContractDeployBackend, _a1 bool) *ChainAccess_EVMClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChainAccess_EVMClient_Call) RunAndReturn(run func(uint64) (sdk.ContractDeployBackend, bool)) *ChainAccess_EVMClient_Call {
	_c.Call.Return(run)
	return _c
}

// Selectors provides a mock function with no fields
func (_m *ChainAccess) Selectors() []uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Selectors")
	}

	var r0 []uint64
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	return r0
}

// ChainAccess_Selectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Selectors'
type ChainAccess_Selectors_Call struct {
	*mock.Call
}

// Selectors is a helper method to define mock.On call
func (_e *ChainAccess_Expecter) Selectors() *ChainAccess_Selectors_Call {
	return &ChainAccess_Selectors_Call{Call: _e.mock.On("Selectors")}
}

func (_c *ChainAccess_Selectors_Call) Run(run func()) *ChainAccess_Selectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChainAccess_Selectors_Call) Return(_a0 []uint64) *ChainAccess_Selectors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChainAccess_Selectors_Call) RunAndReturn(run func() []uint64) *ChainAccess_Selectors_Call {
	_c.Call.Return(run)
	return _c
}

// SolanaClient provides a mock function with given fields: selector
func (_m *ChainAccess) SolanaClient(selector uint64) (*rpc.Client, bool) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for SolanaClient")
	}

	var r0 *rpc.Client
	var r1 bool
	if rf, ok := ret.Get(0).(func(uint64) (*rpc.Client, bool)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(uint64) *rpc.Client); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ChainAccess_SolanaClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SolanaClient'
type ChainAccess_SolanaClient_Call struct {
	*mock.Call
}

// SolanaClient is a helper method to define mock.On call
//   - selector uint64
func (_e *ChainAccess_Expecter) SolanaClient(selector interface{}) *ChainAccess_SolanaClient_Call {
	return &ChainAccess_SolanaClient_Call{Call: _e.mock.On("SolanaClient", selector)}
}

func (_c *ChainAccess_SolanaClient_Call) Run(run func(selector uint64)) *ChainAccess_SolanaClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ChainAccess_SolanaClient_Call) Return(_a0 *rpc.Client, _a1 bool) *ChainAccess_SolanaClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChainAccess_SolanaClient_Call) RunAndReturn(run func(uint64) (*rpc.Client, bool)) *ChainAccess_SolanaClient_Call {
	_c.Call.Return(run)
	return _c
}

// Sui provides a mock function with given fields: selector
func (_m *ChainAccess) Sui(selector uint64) (sui.ISuiAPI, sdk.SuiSigner, bool) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for Sui")
	}

	var r0 sui.ISuiAPI
	var r1 sdk.SuiSigner
	var r2 bool
	if rf, ok := ret.Get(0).(func(uint64) (sui.ISuiAPI, sdk.SuiSigner, bool)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(uint64) sui.ISuiAPI); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sui.ISuiAPI)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) sdk.SuiSigner); ok {
		r1 = rf(selector)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(sdk.SuiSigner)
		}
	}

	if rf, ok := ret.Get(2).(func(uint64) bool); ok {
		r2 = rf(selector)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// ChainAccess_Sui_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sui'
type ChainAccess_Sui_Call struct {
	*mock.Call
}

// Sui is a helper method to define mock.On call
//   - selector uint64
func (_e *ChainAccess_Expecter) Sui(selector interface{}) *ChainAccess_Sui_Call {
	return &ChainAccess_Sui_Call{Call: _e.mock.On("Sui", selector)}
}

func (_c *ChainAccess_Sui_Call) Run(run func(selector uint64)) *ChainAccess_Sui_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ChainAccess_Sui_Call) Return(_a0 sui.ISuiAPI, _a1 sdk.SuiSigner, _a2 bool) *ChainAccess_Sui_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ChainAccess_Sui_Call) RunAndReturn(run func(uint64) (sui.ISuiAPI, sdk.SuiSigner, bool)) *ChainAccess_Sui_Call {
	_c.Call.Return(run)
	return _c
}

// NewChainAccess creates a new instance of ChainAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChainAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChainAccess {
	mock := &ChainAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
