// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	aptos "github.com/aptos-labs/aptos-go-sdk"
	mock "github.com/stretchr/testify/mock"
)

// ChainClient is an autogenerated mock type for the ChainClient type
type ChainClient struct {
	mock.Mock
}

type ChainClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ChainClient) EXPECT() *ChainClient_Expecter {
	return &ChainClient_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function with no fields
func (_m *ChainClient) GetClient() aptos.AptosRpcClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 aptos.AptosRpcClient
	if rf, ok := ret.Get(0).(func() aptos.AptosRpcClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aptos.AptosRpcClient)
		}
	}

	return r0
}

// ChainClient_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type ChainClient_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *ChainClient_Expecter) GetClient() *ChainClient_GetClient_Call {
	return &ChainClient_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *ChainClient_GetClient_Call) Run(run func()) *ChainClient_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChainClient_GetClient_Call) Return(_a0 aptos.AptosRpcClient) *ChainClient_GetClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChainClient_GetClient_Call) RunAndReturn(run func() aptos.AptosRpcClient) *ChainClient_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewChainClient creates a new instance of ChainClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChainClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChainClient {
	mock := &ChainClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
