// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/smartcontractkit/mcms/types"
)

// ConfigTransformer is an autogenerated mock type for the ConfigTransformer type
type ConfigTransformer[R interface{}, C interface{}] struct {
	mock.Mock
}

type ConfigTransformer_Expecter[R interface{}, C interface{}] struct {
	mock *mock.Mock
}

func (_m *ConfigTransformer[R, C]) EXPECT() *ConfigTransformer_Expecter[R, C] {
	return &ConfigTransformer_Expecter[R, C]{mock: &_m.Mock}
}

// ToChainConfig provides a mock function with given fields: cfg, chainSpecificConfig
func (_m *ConfigTransformer[R, C]) ToChainConfig(cfg types.Config, chainSpecificConfig C) (R, error) {
	ret := _m.Called(cfg, chainSpecificConfig)

	if len(ret) == 0 {
		panic("no return value specified for ToChainConfig")
	}

	var r0 R
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Config, C) (R, error)); ok {
		return rf(cfg, chainSpecificConfig)
	}
	if rf, ok := ret.Get(0).(func(types.Config, C) R); ok {
		r0 = rf(cfg, chainSpecificConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Config, C) error); ok {
		r1 = rf(cfg, chainSpecificConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigTransformer_ToChainConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToChainConfig'
type ConfigTransformer_ToChainConfig_Call[R interface{}, C interface{}] struct {
	*mock.Call
}

// ToChainConfig is a helper method to define mock.On call
//   - cfg types.Config
//   - chainSpecificConfig C
func (_e *ConfigTransformer_Expecter[R, C]) ToChainConfig(cfg interface{}, chainSpecificConfig interface{}) *ConfigTransformer_ToChainConfig_Call[R, C] {
	return &ConfigTransformer_ToChainConfig_Call[R, C]{Call: _e.mock.On("ToChainConfig", cfg, chainSpecificConfig)}
}

func (_c *ConfigTransformer_ToChainConfig_Call[R, C]) Run(run func(cfg types.Config, chainSpecificConfig C)) *ConfigTransformer_ToChainConfig_Call[R, C] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Config), args[1].(C))
	})
	return _c
}

func (_c *ConfigTransformer_ToChainConfig_Call[R, C]) Return(_a0 R, _a1 error) *ConfigTransformer_ToChainConfig_Call[R, C] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConfigTransformer_ToChainConfig_Call[R, C]) RunAndReturn(run func(types.Config, C) (R, error)) *ConfigTransformer_ToChainConfig_Call[R, C] {
	_c.Call.Return(run)
	return _c
}

// ToConfig provides a mock function with given fields: onchainConfig
func (_m *ConfigTransformer[R, C]) ToConfig(onchainConfig R) (*types.Config, error) {
	ret := _m.Called(onchainConfig)

	if len(ret) == 0 {
		panic("no return value specified for ToConfig")
	}

	var r0 *types.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(R) (*types.Config, error)); ok {
		return rf(onchainConfig)
	}
	if rf, ok := ret.Get(0).(func(R) *types.Config); ok {
		r0 = rf(onchainConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(R) error); ok {
		r1 = rf(onchainConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigTransformer_ToConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToConfig'
type ConfigTransformer_ToConfig_Call[R interface{}, C interface{}] struct {
	*mock.Call
}

// ToConfig is a helper method to define mock.On call
//   - onchainConfig R
func (_e *ConfigTransformer_Expecter[R, C]) ToConfig(onchainConfig interface{}) *ConfigTransformer_ToConfig_Call[R, C] {
	return &ConfigTransformer_ToConfig_Call[R, C]{Call: _e.mock.On("ToConfig", onchainConfig)}
}

func (_c *ConfigTransformer_ToConfig_Call[R, C]) Run(run func(onchainConfig R)) *ConfigTransformer_ToConfig_Call[R, C] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(R))
	})
	return _c
}

func (_c *ConfigTransformer_ToConfig_Call[R, C]) Return(_a0 *types.Config, _a1 error) *ConfigTransformer_ToConfig_Call[R, C] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConfigTransformer_ToConfig_Call[R, C]) RunAndReturn(run func(R) (*types.Config, error)) *ConfigTransformer_ToConfig_Call[R, C] {
	_c.Call.Return(run)
	return _c
}

// NewConfigTransformer creates a new instance of ConfigTransformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigTransformer[R interface{}, C interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigTransformer[R, C] {
	mock := &ConfigTransformer[R, C]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
