// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"

	types "github.com/smartcontractkit/mcms/types"
)

// OperationID is an autogenerated mock type for the OperationID type
type OperationID struct {
	mock.Mock
}

type OperationID_Expecter struct {
	mock *mock.Mock
}

func (_m *OperationID) EXPECT() *OperationID_Expecter {
	return &OperationID_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *OperationID) Execute(_a0 types.BatchOperation, _a1 types.TimelockAction, _a2 common.Hash, _a3 common.Hash) (common.Hash, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 common.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(types.BatchOperation, types.TimelockAction, common.Hash, common.Hash) (common.Hash, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(types.BatchOperation, types.TimelockAction, common.Hash, common.Hash) common.Hash); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(types.BatchOperation, types.TimelockAction, common.Hash, common.Hash) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OperationID_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type OperationID_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 types.BatchOperation
//   - _a1 types.TimelockAction
//   - _a2 common.Hash
//   - _a3 common.Hash
func (_e *OperationID_Expecter) Execute(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *OperationID_Execute_Call {
	return &OperationID_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1, _a2, _a3)}
}

func (_c *OperationID_Execute_Call) Run(run func(_a0 types.BatchOperation, _a1 types.TimelockAction, _a2 common.Hash, _a3 common.Hash)) *OperationID_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.BatchOperation), args[1].(types.TimelockAction), args[2].(common.Hash), args[3].(common.Hash))
	})
	return _c
}

func (_c *OperationID_Execute_Call) Return(_a0 common.Hash, _a1 error) *OperationID_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OperationID_Execute_Call) RunAndReturn(run func(types.BatchOperation, types.TimelockAction, common.Hash, common.Hash) (common.Hash, error)) *OperationID_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewOperationID creates a new instance of OperationID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationID(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationID {
	mock := &OperationID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
