// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	sdk "github.com/smartcontractkit/mcms/sdk"
	mock "github.com/stretchr/testify/mock"

	sui "github.com/block-vision/sui-go-sdk/sui"
)

// SuiChainClient is an autogenerated mock type for the SuiChainClient type
type SuiChainClient struct {
	mock.Mock
}

type SuiChainClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SuiChainClient) EXPECT() *SuiChainClient_Expecter {
	return &SuiChainClient_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function with no fields
func (_m *SuiChainClient) GetClient() sui.ISuiAPI {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 sui.ISuiAPI
	if rf, ok := ret.Get(0).(func() sui.ISuiAPI); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sui.ISuiAPI)
		}
	}

	return r0
}

// SuiChainClient_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type SuiChainClient_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *SuiChainClient_Expecter) GetClient() *SuiChainClient_GetClient_Call {
	return &SuiChainClient_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *SuiChainClient_GetClient_Call) Run(run func()) *SuiChainClient_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SuiChainClient_GetClient_Call) Return(_a0 sui.ISuiAPI) *SuiChainClient_GetClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SuiChainClient_GetClient_Call) RunAndReturn(run func() sui.ISuiAPI) *SuiChainClient_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetSigner provides a mock function with no fields
func (_m *SuiChainClient) GetSigner() sdk.SuiSigner {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSigner")
	}

	var r0 sdk.SuiSigner
	if rf, ok := ret.Get(0).(func() sdk.SuiSigner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sdk.SuiSigner)
		}
	}

	return r0
}

// SuiChainClient_GetSigner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSigner'
type SuiChainClient_GetSigner_Call struct {
	*mock.Call
}

// GetSigner is a helper method to define mock.On call
func (_e *SuiChainClient_Expecter) GetSigner() *SuiChainClient_GetSigner_Call {
	return &SuiChainClient_GetSigner_Call{Call: _e.mock.On("GetSigner")}
}

func (_c *SuiChainClient_GetSigner_Call) Run(run func()) *SuiChainClient_GetSigner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SuiChainClient_GetSigner_Call) Return(_a0 sdk.SuiSigner) *SuiChainClient_GetSigner_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SuiChainClient_GetSigner_Call) RunAndReturn(run func() sdk.SuiSigner) *SuiChainClient_GetSigner_Call {
	_c.Call.Return(run)
	return _c
}

// NewSuiChainClient creates a new instance of SuiChainClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSuiChainClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SuiChainClient {
	mock := &SuiChainClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
