// Code generated by mockery v2.48.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TimelockInspector is an autogenerated mock type for the TimelockInspector type
type TimelockInspector[T any] struct {
	mock.Mock
}

type TimelockInspector_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *TimelockInspector[T]) EXPECT() *TimelockInspector_Expecter[T] {
	return &TimelockInspector_Expecter[T]{mock: &_m.Mock}
}

// GetBypassers provides a mock function with given fields: ctx, address
func (_m *TimelockInspector[T]) GetBypassers(ctx context.Context, address string) ([]T, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetBypassers")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]T, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []T); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelockInspector_GetBypassers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBypassers'
type TimelockInspector_GetBypassers_Call[T any] struct {
	*mock.Call
}

// GetBypassers is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *TimelockInspector_Expecter[T]) GetBypassers(ctx interface{}, address interface{}) *TimelockInspector_GetBypassers_Call[T] {
	return &TimelockInspector_GetBypassers_Call[T]{Call: _e.mock.On("GetBypassers", ctx, address)}
}

func (_c *TimelockInspector_GetBypassers_Call[T]) Run(run func(ctx context.Context, address string)) *TimelockInspector_GetBypassers_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TimelockInspector_GetBypassers_Call[T]) Return(_a0 []T, _a1 error) *TimelockInspector_GetBypassers_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelockInspector_GetBypassers_Call[T]) RunAndReturn(run func(context.Context, string) ([]T, error)) *TimelockInspector_GetBypassers_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetCancellers provides a mock function with given fields: ctx, address
func (_m *TimelockInspector[T]) GetCancellers(ctx context.Context, address string) ([]T, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetCancellers")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]T, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []T); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelockInspector_GetCancellers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCancellers'
type TimelockInspector_GetCancellers_Call[T any] struct {
	*mock.Call
}

// GetCancellers is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *TimelockInspector_Expecter[T]) GetCancellers(ctx interface{}, address interface{}) *TimelockInspector_GetCancellers_Call[T] {
	return &TimelockInspector_GetCancellers_Call[T]{Call: _e.mock.On("GetCancellers", ctx, address)}
}

func (_c *TimelockInspector_GetCancellers_Call[T]) Run(run func(ctx context.Context, address string)) *TimelockInspector_GetCancellers_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TimelockInspector_GetCancellers_Call[T]) Return(_a0 []T, _a1 error) *TimelockInspector_GetCancellers_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelockInspector_GetCancellers_Call[T]) RunAndReturn(run func(context.Context, string) ([]T, error)) *TimelockInspector_GetCancellers_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetExecutors provides a mock function with given fields: ctx, address
func (_m *TimelockInspector[T]) GetExecutors(ctx context.Context, address string) ([]T, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutors")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]T, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []T); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelockInspector_GetExecutors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutors'
type TimelockInspector_GetExecutors_Call[T any] struct {
	*mock.Call
}

// GetExecutors is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *TimelockInspector_Expecter[T]) GetExecutors(ctx interface{}, address interface{}) *TimelockInspector_GetExecutors_Call[T] {
	return &TimelockInspector_GetExecutors_Call[T]{Call: _e.mock.On("GetExecutors", ctx, address)}
}

func (_c *TimelockInspector_GetExecutors_Call[T]) Run(run func(ctx context.Context, address string)) *TimelockInspector_GetExecutors_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TimelockInspector_GetExecutors_Call[T]) Return(_a0 []T, _a1 error) *TimelockInspector_GetExecutors_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelockInspector_GetExecutors_Call[T]) RunAndReturn(run func(context.Context, string) ([]T, error)) *TimelockInspector_GetExecutors_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetProposers provides a mock function with given fields: ctx, address
func (_m *TimelockInspector[T]) GetProposers(ctx context.Context, address string) ([]T, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetProposers")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]T, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []T); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelockInspector_GetProposers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProposers'
type TimelockInspector_GetProposers_Call[T any] struct {
	*mock.Call
}

// GetProposers is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *TimelockInspector_Expecter[T]) GetProposers(ctx interface{}, address interface{}) *TimelockInspector_GetProposers_Call[T] {
	return &TimelockInspector_GetProposers_Call[T]{Call: _e.mock.On("GetProposers", ctx, address)}
}

func (_c *TimelockInspector_GetProposers_Call[T]) Run(run func(ctx context.Context, address string)) *TimelockInspector_GetProposers_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TimelockInspector_GetProposers_Call[T]) Return(_a0 []T, _a1 error) *TimelockInspector_GetProposers_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelockInspector_GetProposers_Call[T]) RunAndReturn(run func(context.Context, string) ([]T, error)) *TimelockInspector_GetProposers_Call[T] {
	_c.Call.Return(run)
	return _c
}

// IsOperation provides a mock function with given fields: ctx, address, opID
func (_m *TimelockInspector[T]) IsOperation(ctx context.Context, address string, opID [32]byte) (bool, error) {
	ret := _m.Called(ctx, address, opID)

	if len(ret) == 0 {
		panic("no return value specified for IsOperation")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, [32]byte) (bool, error)); ok {
		return rf(ctx, address, opID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, [32]byte) bool); ok {
		r0 = rf(ctx, address, opID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, [32]byte) error); ok {
		r1 = rf(ctx, address, opID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelockInspector_IsOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOperation'
type TimelockInspector_IsOperation_Call[T any] struct {
	*mock.Call
}

// IsOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - opID [32]byte
func (_e *TimelockInspector_Expecter[T]) IsOperation(ctx interface{}, address interface{}, opID interface{}) *TimelockInspector_IsOperation_Call[T] {
	return &TimelockInspector_IsOperation_Call[T]{Call: _e.mock.On("IsOperation", ctx, address, opID)}
}

func (_c *TimelockInspector_IsOperation_Call[T]) Run(run func(ctx context.Context, address string, opID [32]byte)) *TimelockInspector_IsOperation_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([32]byte))
	})
	return _c
}

func (_c *TimelockInspector_IsOperation_Call[T]) Return(_a0 bool, _a1 error) *TimelockInspector_IsOperation_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelockInspector_IsOperation_Call[T]) RunAndReturn(run func(context.Context, string, [32]byte) (bool, error)) *TimelockInspector_IsOperation_Call[T] {
	_c.Call.Return(run)
	return _c
}

// IsOperationDone provides a mock function with given fields: ctx, address, opID
func (_m *TimelockInspector[T]) IsOperationDone(ctx context.Context, address string, opID [32]byte) (bool, error) {
	ret := _m.Called(ctx, address, opID)

	if len(ret) == 0 {
		panic("no return value specified for IsOperationDone")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, [32]byte) (bool, error)); ok {
		return rf(ctx, address, opID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, [32]byte) bool); ok {
		r0 = rf(ctx, address, opID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, [32]byte) error); ok {
		r1 = rf(ctx, address, opID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelockInspector_IsOperationDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOperationDone'
type TimelockInspector_IsOperationDone_Call[T any] struct {
	*mock.Call
}

// IsOperationDone is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - opID [32]byte
func (_e *TimelockInspector_Expecter[T]) IsOperationDone(ctx interface{}, address interface{}, opID interface{}) *TimelockInspector_IsOperationDone_Call[T] {
	return &TimelockInspector_IsOperationDone_Call[T]{Call: _e.mock.On("IsOperationDone", ctx, address, opID)}
}

func (_c *TimelockInspector_IsOperationDone_Call[T]) Run(run func(ctx context.Context, address string, opID [32]byte)) *TimelockInspector_IsOperationDone_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([32]byte))
	})
	return _c
}

func (_c *TimelockInspector_IsOperationDone_Call[T]) Return(_a0 bool, _a1 error) *TimelockInspector_IsOperationDone_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelockInspector_IsOperationDone_Call[T]) RunAndReturn(run func(context.Context, string, [32]byte) (bool, error)) *TimelockInspector_IsOperationDone_Call[T] {
	_c.Call.Return(run)
	return _c
}

// IsOperationPending provides a mock function with given fields: ctx, address, opID
func (_m *TimelockInspector[T]) IsOperationPending(ctx context.Context, address string, opID [32]byte) (bool, error) {
	ret := _m.Called(ctx, address, opID)

	if len(ret) == 0 {
		panic("no return value specified for IsOperationPending")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, [32]byte) (bool, error)); ok {
		return rf(ctx, address, opID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, [32]byte) bool); ok {
		r0 = rf(ctx, address, opID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, [32]byte) error); ok {
		r1 = rf(ctx, address, opID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelockInspector_IsOperationPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOperationPending'
type TimelockInspector_IsOperationPending_Call[T any] struct {
	*mock.Call
}

// IsOperationPending is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - opID [32]byte
func (_e *TimelockInspector_Expecter[T]) IsOperationPending(ctx interface{}, address interface{}, opID interface{}) *TimelockInspector_IsOperationPending_Call[T] {
	return &TimelockInspector_IsOperationPending_Call[T]{Call: _e.mock.On("IsOperationPending", ctx, address, opID)}
}

func (_c *TimelockInspector_IsOperationPending_Call[T]) Run(run func(ctx context.Context, address string, opID [32]byte)) *TimelockInspector_IsOperationPending_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([32]byte))
	})
	return _c
}

func (_c *TimelockInspector_IsOperationPending_Call[T]) Return(_a0 bool, _a1 error) *TimelockInspector_IsOperationPending_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelockInspector_IsOperationPending_Call[T]) RunAndReturn(run func(context.Context, string, [32]byte) (bool, error)) *TimelockInspector_IsOperationPending_Call[T] {
	_c.Call.Return(run)
	return _c
}

// IsOperationReady provides a mock function with given fields: ctx, address, opID
func (_m *TimelockInspector[T]) IsOperationReady(ctx context.Context, address string, opID [32]byte) (bool, error) {
	ret := _m.Called(ctx, address, opID)

	if len(ret) == 0 {
		panic("no return value specified for IsOperationReady")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, [32]byte) (bool, error)); ok {
		return rf(ctx, address, opID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, [32]byte) bool); ok {
		r0 = rf(ctx, address, opID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, [32]byte) error); ok {
		r1 = rf(ctx, address, opID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelockInspector_IsOperationReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOperationReady'
type TimelockInspector_IsOperationReady_Call[T any] struct {
	*mock.Call
}

// IsOperationReady is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - opID [32]byte
func (_e *TimelockInspector_Expecter[T]) IsOperationReady(ctx interface{}, address interface{}, opID interface{}) *TimelockInspector_IsOperationReady_Call[T] {
	return &TimelockInspector_IsOperationReady_Call[T]{Call: _e.mock.On("IsOperationReady", ctx, address, opID)}
}

func (_c *TimelockInspector_IsOperationReady_Call[T]) Run(run func(ctx context.Context, address string, opID [32]byte)) *TimelockInspector_IsOperationReady_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([32]byte))
	})
	return _c
}

func (_c *TimelockInspector_IsOperationReady_Call[T]) Return(_a0 bool, _a1 error) *TimelockInspector_IsOperationReady_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelockInspector_IsOperationReady_Call[T]) RunAndReturn(run func(context.Context, string, [32]byte) (bool, error)) *TimelockInspector_IsOperationReady_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewTimelockInspector creates a new instance of TimelockInspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimelockInspector[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *TimelockInspector[T] {
	mock := &TimelockInspector[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
