// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/smartcontractkit/mcms/types"
)

// TimelockConfigurer is an autogenerated mock type for the TimelockConfigurer type
type TimelockConfigurer struct {
	mock.Mock
}

type TimelockConfigurer_Expecter struct {
	mock *mock.Mock
}

func (_m *TimelockConfigurer) EXPECT() *TimelockConfigurer_Expecter {
	return &TimelockConfigurer_Expecter{mock: &_m.Mock}
}

// UpdateDelay provides a mock function with given fields: ctx, timelockAddress, newDelay
func (_m *TimelockConfigurer) UpdateDelay(ctx context.Context, timelockAddress string, newDelay uint64) (types.TransactionResult, error) {
	ret := _m.Called(ctx, timelockAddress, newDelay)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDelay")
	}

	var r0 types.TransactionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64) (types.TransactionResult, error)); ok {
		return rf(ctx, timelockAddress, newDelay)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64) types.TransactionResult); ok {
		r0 = rf(ctx, timelockAddress, newDelay)
	} else {
		r0 = ret.Get(0).(types.TransactionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint64) error); ok {
		r1 = rf(ctx, timelockAddress, newDelay)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimelockConfigurer_UpdateDelay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDelay'
type TimelockConfigurer_UpdateDelay_Call struct {
	*mock.Call
}

// UpdateDelay is a helper method to define mock.On call
//   - ctx context.Context
//   - timelockAddress string
//   - newDelay uint64
func (_e *TimelockConfigurer_Expecter) UpdateDelay(ctx interface{}, timelockAddress interface{}, newDelay interface{}) *TimelockConfigurer_UpdateDelay_Call {
	return &TimelockConfigurer_UpdateDelay_Call{Call: _e.mock.On("UpdateDelay", ctx, timelockAddress, newDelay)}
}

func (_c *TimelockConfigurer_UpdateDelay_Call) Run(run func(ctx context.Context, timelockAddress string, newDelay uint64)) *TimelockConfigurer_UpdateDelay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint64))
	})
	return _c
}

func (_c *TimelockConfigurer_UpdateDelay_Call) Return(_a0 types.TransactionResult, _a1 error) *TimelockConfigurer_UpdateDelay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TimelockConfigurer_UpdateDelay_Call) RunAndReturn(run func(context.Context, string, uint64) (types.TransactionResult, error)) *TimelockConfigurer_UpdateDelay_Call {
	_c.Call.Return(run)
	return _c
}

// NewTimelockConfigurer creates a new instance of TimelockConfigurer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimelockConfigurer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimelockConfigurer {
	mock := &TimelockConfigurer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
