[evm_config]
chain_id = "31337"
image = "f4hrenh9it/foundry:latest"
port = "8545"
type = "anvil"

# Anvil command line parameters
docker_cmd_params = [
    "--accounts=1",
    "--balance=100000",
    "--mnemonic test test test test test test test test test test test junk"
]
[evm_test_data]
mnemonic = "test test test test test test test test test test test junk"