// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"
)

// Inspector is an autogenerated mock type for the Inspector type
type Inspector struct {
	mock.Mock
}

type Inspector_Expecter struct {
	mock *mock.Mock
}

func (_m *Inspector) EXPECT() *Inspector_Expecter {
	return &Inspector_Expecter{mock: &_m.Mock}
}

// GetBypassers provides a mock function with given fields: address
func (_m *Inspector) GetBypassers(address string) ([]common.Address, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for GetBypassers")
	}

	var r0 []common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]common.Address, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) []common.Address); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Inspector_GetBypassers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBypassers'
type Inspector_GetBypassers_Call struct {
	*mock.Call
}

// GetBypassers is a helper method to define mock.On call
//   - address string
func (_e *Inspector_Expecter) GetBypassers(address interface{}) *Inspector_GetBypassers_Call {
	return &Inspector_GetBypassers_Call{Call: _e.mock.On("GetBypassers", address)}
}

func (_c *Inspector_GetBypassers_Call) Run(run func(address string)) *Inspector_GetBypassers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Inspector_GetBypassers_Call) Return(_a0 []common.Address, _a1 error) *Inspector_GetBypassers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Inspector_GetBypassers_Call) RunAndReturn(run func(string) ([]common.Address, error)) *Inspector_GetBypassers_Call {
	_c.Call.Return(run)
	return _c
}

// GetCancellers provides a mock function with given fields: address
func (_m *Inspector) GetCancellers(address string) ([]common.Address, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for GetCancellers")
	}

	var r0 []common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]common.Address, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) []common.Address); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Inspector_GetCancellers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCancellers'
type Inspector_GetCancellers_Call struct {
	*mock.Call
}

// GetCancellers is a helper method to define mock.On call
//   - address string
func (_e *Inspector_Expecter) GetCancellers(address interface{}) *Inspector_GetCancellers_Call {
	return &Inspector_GetCancellers_Call{Call: _e.mock.On("GetCancellers", address)}
}

func (_c *Inspector_GetCancellers_Call) Run(run func(address string)) *Inspector_GetCancellers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Inspector_GetCancellers_Call) Return(_a0 []common.Address, _a1 error) *Inspector_GetCancellers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Inspector_GetCancellers_Call) RunAndReturn(run func(string) ([]common.Address, error)) *Inspector_GetCancellers_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutors provides a mock function with given fields: address
func (_m *Inspector) GetExecutors(address string) ([]common.Address, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutors")
	}

	var r0 []common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]common.Address, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) []common.Address); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Inspector_GetExecutors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutors'
type Inspector_GetExecutors_Call struct {
	*mock.Call
}

// GetExecutors is a helper method to define mock.On call
//   - address string
func (_e *Inspector_Expecter) GetExecutors(address interface{}) *Inspector_GetExecutors_Call {
	return &Inspector_GetExecutors_Call{Call: _e.mock.On("GetExecutors", address)}
}

func (_c *Inspector_GetExecutors_Call) Run(run func(address string)) *Inspector_GetExecutors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Inspector_GetExecutors_Call) Return(_a0 []common.Address, _a1 error) *Inspector_GetExecutors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Inspector_GetExecutors_Call) RunAndReturn(run func(string) ([]common.Address, error)) *Inspector_GetExecutors_Call {
	_c.Call.Return(run)
	return _c
}

// GetProposers provides a mock function with given fields: address
func (_m *Inspector) GetProposers(address string) ([]common.Address, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for GetProposers")
	}

	var r0 []common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]common.Address, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) []common.Address); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Inspector_GetProposers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProposers'
type Inspector_GetProposers_Call struct {
	*mock.Call
}

// GetProposers is a helper method to define mock.On call
//   - address string
func (_e *Inspector_Expecter) GetProposers(address interface{}) *Inspector_GetProposers_Call {
	return &Inspector_GetProposers_Call{Call: _e.mock.On("GetProposers", address)}
}

func (_c *Inspector_GetProposers_Call) Run(run func(address string)) *Inspector_GetProposers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Inspector_GetProposers_Call) Return(_a0 []common.Address, _a1 error) *Inspector_GetProposers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Inspector_GetProposers_Call) RunAndReturn(run func(string) ([]common.Address, error)) *Inspector_GetProposers_Call {
	_c.Call.Return(run)
	return _c
}

// IsOperation provides a mock function with given fields: address, opId
func (_m *Inspector) IsOperation(address string, opId [32]byte) (bool, error) {
	ret := _m.Called(address, opId)

	if len(ret) == 0 {
		panic("no return value specified for IsOperation")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, [32]byte) (bool, error)); ok {
		return rf(address, opId)
	}
	if rf, ok := ret.Get(0).(func(string, [32]byte) bool); ok {
		r0 = rf(address, opId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, [32]byte) error); ok {
		r1 = rf(address, opId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Inspector_IsOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOperation'
type Inspector_IsOperation_Call struct {
	*mock.Call
}

// IsOperation is a helper method to define mock.On call
//   - address string
//   - opId [32]byte
func (_e *Inspector_Expecter) IsOperation(address interface{}, opId interface{}) *Inspector_IsOperation_Call {
	return &Inspector_IsOperation_Call{Call: _e.mock.On("IsOperation", address, opId)}
}

func (_c *Inspector_IsOperation_Call) Run(run func(address string, opId [32]byte)) *Inspector_IsOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([32]byte))
	})
	return _c
}

func (_c *Inspector_IsOperation_Call) Return(_a0 bool, _a1 error) *Inspector_IsOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Inspector_IsOperation_Call) RunAndReturn(run func(string, [32]byte) (bool, error)) *Inspector_IsOperation_Call {
	_c.Call.Return(run)
	return _c
}

// IsOperationDone provides a mock function with given fields: address, opId
func (_m *Inspector) IsOperationDone(address string, opId [32]byte) (bool, error) {
	ret := _m.Called(address, opId)

	if len(ret) == 0 {
		panic("no return value specified for IsOperationDone")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, [32]byte) (bool, error)); ok {
		return rf(address, opId)
	}
	if rf, ok := ret.Get(0).(func(string, [32]byte) bool); ok {
		r0 = rf(address, opId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, [32]byte) error); ok {
		r1 = rf(address, opId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Inspector_IsOperationDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOperationDone'
type Inspector_IsOperationDone_Call struct {
	*mock.Call
}

// IsOperationDone is a helper method to define mock.On call
//   - address string
//   - opId [32]byte
func (_e *Inspector_Expecter) IsOperationDone(address interface{}, opId interface{}) *Inspector_IsOperationDone_Call {
	return &Inspector_IsOperationDone_Call{Call: _e.mock.On("IsOperationDone", address, opId)}
}

func (_c *Inspector_IsOperationDone_Call) Run(run func(address string, opId [32]byte)) *Inspector_IsOperationDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([32]byte))
	})
	return _c
}

func (_c *Inspector_IsOperationDone_Call) Return(_a0 bool, _a1 error) *Inspector_IsOperationDone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Inspector_IsOperationDone_Call) RunAndReturn(run func(string, [32]byte) (bool, error)) *Inspector_IsOperationDone_Call {
	_c.Call.Return(run)
	return _c
}

// IsOperationPending provides a mock function with given fields: address, opId
func (_m *Inspector) IsOperationPending(address string, opId [32]byte) (bool, error) {
	ret := _m.Called(address, opId)

	if len(ret) == 0 {
		panic("no return value specified for IsOperationPending")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, [32]byte) (bool, error)); ok {
		return rf(address, opId)
	}
	if rf, ok := ret.Get(0).(func(string, [32]byte) bool); ok {
		r0 = rf(address, opId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, [32]byte) error); ok {
		r1 = rf(address, opId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Inspector_IsOperationPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOperationPending'
type Inspector_IsOperationPending_Call struct {
	*mock.Call
}

// IsOperationPending is a helper method to define mock.On call
//   - address string
//   - opId [32]byte
func (_e *Inspector_Expecter) IsOperationPending(address interface{}, opId interface{}) *Inspector_IsOperationPending_Call {
	return &Inspector_IsOperationPending_Call{Call: _e.mock.On("IsOperationPending", address, opId)}
}

func (_c *Inspector_IsOperationPending_Call) Run(run func(address string, opId [32]byte)) *Inspector_IsOperationPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([32]byte))
	})
	return _c
}

func (_c *Inspector_IsOperationPending_Call) Return(_a0 bool, _a1 error) *Inspector_IsOperationPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Inspector_IsOperationPending_Call) RunAndReturn(run func(string, [32]byte) (bool, error)) *Inspector_IsOperationPending_Call {
	_c.Call.Return(run)
	return _c
}

// IsOperationReady provides a mock function with given fields: address, opId
func (_m *Inspector) IsOperationReady(address string, opId [32]byte) (bool, error) {
	ret := _m.Called(address, opId)

	if len(ret) == 0 {
		panic("no return value specified for IsOperationReady")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, [32]byte) (bool, error)); ok {
		return rf(address, opId)
	}
	if rf, ok := ret.Get(0).(func(string, [32]byte) bool); ok {
		r0 = rf(address, opId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, [32]byte) error); ok {
		r1 = rf(address, opId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Inspector_IsOperationReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOperationReady'
type Inspector_IsOperationReady_Call struct {
	*mock.Call
}

// IsOperationReady is a helper method to define mock.On call
//   - address string
//   - opId [32]byte
func (_e *Inspector_Expecter) IsOperationReady(address interface{}, opId interface{}) *Inspector_IsOperationReady_Call {
	return &Inspector_IsOperationReady_Call{Call: _e.mock.On("IsOperationReady", address, opId)}
}

func (_c *Inspector_IsOperationReady_Call) Run(run func(address string, opId [32]byte)) *Inspector_IsOperationReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([32]byte))
	})
	return _c
}

func (_c *Inspector_IsOperationReady_Call) Return(_a0 bool, _a1 error) *Inspector_IsOperationReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Inspector_IsOperationReady_Call) RunAndReturn(run func(string, [32]byte) (bool, error)) *Inspector_IsOperationReady_Call {
	_c.Call.Return(run)
	return _c
}

// NewInspector creates a new instance of Inspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInspector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Inspector {
	mock := &Inspector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
