// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	aptos "github.com/aptos-labs/aptos-go-sdk"

	evm "github.com/smartcontractkit/mcms/sdk/evm"

	mock "github.com/stretchr/testify/mock"

	rpc "github.com/gagliardetto/solana-go/rpc"

	sdksui "github.com/smartcontractkit/mcms/sdk/sui"

	sui "github.com/block-vision/sui-go-sdk/sui"
)

// ChainAccessor is an autogenerated mock type for the ChainAccessor type
type ChainAccessor struct {
	mock.Mock
}

type ChainAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *ChainAccessor) EXPECT() *ChainAccessor_Expecter {
	return &ChainAccessor_Expecter{mock: &_m.Mock}
}

// AptosClient provides a mock function with given fields: selector
func (_m *ChainAccessor) AptosClient(selector uint64) (aptos.AptosRpcClient, bool) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for AptosClient")
	}

	var r0 aptos.AptosRpcClient
	var r1 bool
	if rf, ok := ret.Get(0).(func(uint64) (aptos.AptosRpcClient, bool)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(uint64) aptos.AptosRpcClient); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aptos.AptosRpcClient)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ChainAccessor_AptosClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AptosClient'
type ChainAccessor_AptosClient_Call struct {
	*mock.Call
}

// AptosClient is a helper method to define mock.On call
//   - selector uint64
func (_e *ChainAccessor_Expecter) AptosClient(selector interface{}) *ChainAccessor_AptosClient_Call {
	return &ChainAccessor_AptosClient_Call{Call: _e.mock.On("AptosClient", selector)}
}

func (_c *ChainAccessor_AptosClient_Call) Run(run func(selector uint64)) *ChainAccessor_AptosClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ChainAccessor_AptosClient_Call) Return(_a0 aptos.AptosRpcClient, _a1 bool) *ChainAccessor_AptosClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChainAccessor_AptosClient_Call) RunAndReturn(run func(uint64) (aptos.AptosRpcClient, bool)) *ChainAccessor_AptosClient_Call {
	_c.Call.Return(run)
	return _c
}

// EVMClient provides a mock function with given fields: selector
func (_m *ChainAccessor) EVMClient(selector uint64) (evm.ContractDeployBackend, bool) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for EVMClient")
	}

	var r0 evm.ContractDeployBackend
	var r1 bool
	if rf, ok := ret.Get(0).(func(uint64) (evm.ContractDeployBackend, bool)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(uint64) evm.ContractDeployBackend); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(evm.ContractDeployBackend)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ChainAccessor_EVMClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EVMClient'
type ChainAccessor_EVMClient_Call struct {
	*mock.Call
}

// EVMClient is a helper method to define mock.On call
//   - selector uint64
func (_e *ChainAccessor_Expecter) EVMClient(selector interface{}) *ChainAccessor_EVMClient_Call {
	return &ChainAccessor_EVMClient_Call{Call: _e.mock.On("EVMClient", selector)}
}

func (_c *ChainAccessor_EVMClient_Call) Run(run func(selector uint64)) *ChainAccessor_EVMClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ChainAccessor_EVMClient_Call) Return(_a0 evm.ContractDeployBackend, _a1 bool) *ChainAccessor_EVMClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChainAccessor_EVMClient_Call) RunAndReturn(run func(uint64) (evm.ContractDeployBackend, bool)) *ChainAccessor_EVMClient_Call {
	_c.Call.Return(run)
	return _c
}

// Selectors provides a mock function with no fields
func (_m *ChainAccessor) Selectors() []uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Selectors")
	}

	var r0 []uint64
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	return r0
}

// ChainAccessor_Selectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Selectors'
type ChainAccessor_Selectors_Call struct {
	*mock.Call
}

// Selectors is a helper method to define mock.On call
func (_e *ChainAccessor_Expecter) Selectors() *ChainAccessor_Selectors_Call {
	return &ChainAccessor_Selectors_Call{Call: _e.mock.On("Selectors")}
}

func (_c *ChainAccessor_Selectors_Call) Run(run func()) *ChainAccessor_Selectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChainAccessor_Selectors_Call) Return(_a0 []uint64) *ChainAccessor_Selectors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChainAccessor_Selectors_Call) RunAndReturn(run func() []uint64) *ChainAccessor_Selectors_Call {
	_c.Call.Return(run)
	return _c
}

// SolanaClient provides a mock function with given fields: selector
func (_m *ChainAccessor) SolanaClient(selector uint64) (*rpc.Client, bool) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for SolanaClient")
	}

	var r0 *rpc.Client
	var r1 bool
	if rf, ok := ret.Get(0).(func(uint64) (*rpc.Client, bool)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(uint64) *rpc.Client); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ChainAccessor_SolanaClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SolanaClient'
type ChainAccessor_SolanaClient_Call struct {
	*mock.Call
}

// SolanaClient is a helper method to define mock.On call
//   - selector uint64
func (_e *ChainAccessor_Expecter) SolanaClient(selector interface{}) *ChainAccessor_SolanaClient_Call {
	return &ChainAccessor_SolanaClient_Call{Call: _e.mock.On("SolanaClient", selector)}
}

func (_c *ChainAccessor_SolanaClient_Call) Run(run func(selector uint64)) *ChainAccessor_SolanaClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ChainAccessor_SolanaClient_Call) Return(_a0 *rpc.Client, _a1 bool) *ChainAccessor_SolanaClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChainAccessor_SolanaClient_Call) RunAndReturn(run func(uint64) (*rpc.Client, bool)) *ChainAccessor_SolanaClient_Call {
	_c.Call.Return(run)
	return _c
}

// SuiClient provides a mock function with given fields: selector
func (_m *ChainAccessor) SuiClient(selector uint64) (sui.ISuiAPI, sdksui.SuiSigner, bool) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for SuiClient")
	}

	var r0 sui.ISuiAPI
	var r1 sdksui.SuiSigner
	var r2 bool
	if rf, ok := ret.Get(0).(func(uint64) (sui.ISuiAPI, sdksui.SuiSigner, bool)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(uint64) sui.ISuiAPI); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sui.ISuiAPI)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) sdksui.SuiSigner); ok {
		r1 = rf(selector)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(sdksui.SuiSigner)
		}
	}

	if rf, ok := ret.Get(2).(func(uint64) bool); ok {
		r2 = rf(selector)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// ChainAccessor_SuiClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuiClient'
type ChainAccessor_SuiClient_Call struct {
	*mock.Call
}

// SuiClient is a helper method to define mock.On call
//   - selector uint64
func (_e *ChainAccessor_Expecter) SuiClient(selector interface{}) *ChainAccessor_SuiClient_Call {
	return &ChainAccessor_SuiClient_Call{Call: _e.mock.On("SuiClient", selector)}
}

func (_c *ChainAccessor_SuiClient_Call) Run(run func(selector uint64)) *ChainAccessor_SuiClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ChainAccessor_SuiClient_Call) Return(_a0 sui.ISuiAPI, _a1 sdksui.SuiSigner, _a2 bool) *ChainAccessor_SuiClient_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ChainAccessor_SuiClient_Call) RunAndReturn(run func(uint64) (sui.ISuiAPI, sdksui.SuiSigner, bool)) *ChainAccessor_SuiClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewChainAccessor creates a new instance of ChainAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChainAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChainAccessor {
	mock := &ChainAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
