name: Validate Go Mod Files
permissions:
  contents: read

on:
  pull_request:
  merge_group:

jobs:
  go-mod-validation:
    name: Validate go.mod dependencies
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate go.mod
        uses: smartcontractkit/.github/apps/go-mod-validator@6ff93d190d3499c4889001c181f503c45420497d # go-mod-validator@4.2.0
