name: Validate Go Mod Files
permissions:
  contents: read

on:
  pull_request:
  merge_group:

jobs:
  go-mod-validation:
    name: Validate go.mod dependencies
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate go.mod
        uses: smartcontractkit/.github/apps/go-mod-validator@df37dd4809c8b2979c728ed49960358ed2f8f1ce # go-mod-validator@1.5.0
