name: push-tag-release

on:
  push:
    tags:
      - v*

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  ci-lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-lint
        uses: smartcontractkit/.github/actions/ci-lint-go@ci-lint-go/v4
        with:
          golangci-lint-version: v2.12.2
          golangci-lint-config: .golangci.yml

  ci-lint-e2e:
    name: Lint E2E tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Linting Go
        uses: smartcontractkit/.github/actions/ci-lint-go@ci-lint-go/v4
        with:
          golangci-lint-version: v2.12.2
          golangci-lint-args: --build-tags="e2e"
          golangci-lint-config: .golangci.yml

  ci-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-test
        uses: smartcontractkit/.github/actions/ci-test-go@ci-test-go/v1
